# Generated by Django 4.2.11 on 2024-10-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_book_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="birthday",
            new_name="birthdate",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="user",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="middele_name",
            new_name="middle_name",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="user",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="user",
            new_name="created_by",
        ),
        migrations.RemoveField(
            model_name="book",
            name="translator",
        ),
    ]
