version: '3.9'

services:
  web:
    build: .
    command: uwsgi --ini /code/uwsgi.ini
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
